ALTER TABLE utilisateur
  ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS totp_secret VARCHAR(255),
  ADD COLUMN IF NOT EXISTS backup_codes TEXT,
  ADD COLUMN IF NOT EXISTS mfa_setup_secret VARCHAR(255),
  ADD COLUMN IF NOT EXISTS mfa_setup_secret_created_at TIMESTAMP;
