export const ROLES = {
  CITOYEN: 'CITOYEN',
  AGENT: 'AGENT',
  GESTIONNAIRE: 'GESTIONNAIRE',
  ADMIN: 'ADMIN',
};

export const INTERFACE_TYPES = {
  MOBILE: 'mobile',
  DESKTOP: 'desktop',
};

export const ROLE_LABELS = {
  [ROLES.CITOYEN]: 'Citoyen',
  [ROLES.AGENT]: 'Agent',
  [ROLES.GESTIONNAIRE]: 'Gestionnaire',
  [ROLES.ADMIN]: 'Administrateur',
};

export const PERMISSIONS = {
  SIGNALER_CREATE: 'signaler:create',
  SIGNALER_READ: 'signaler:read',
  SIGNALER_UPDATE: 'signaler:update',
  CONTAINERS_READ: 'containers:read',
  CONTAINERS_UPDATE: 'containers:update',
  TOURNEE_READ: 'tournee:read',
  TOURNEE_UPDATE: 'tournee:update',
  TOURNEE_CREATE: 'tournee:create',
  COLLECTE_CREATE: 'collecte:create',
  USERS_READ: 'users:read',
  ANALYTICS_READ: 'analytics:read',
  PROFILE_READ: 'profile:read',
  PROFILE_UPDATE: 'profile:update',
};

export const ROLE_PERMISSIONS = {
  [ROLES.CITOYEN]: [
    PERMISSIONS.SIGNALER_CREATE,
    PERMISSIONS.SIGNALER_READ,
    PERMISSIONS.CONTAINERS_READ,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
  ],
  [ROLES.AGENT]: [
    PERMISSIONS.SIGNALER_READ,
    PERMISSIONS.SIGNALER_UPDATE,
    PERMISSIONS.CONTAINERS_READ,
    PERMISSIONS.TOURNEE_READ,
    PERMISSIONS.TOURNEE_UPDATE,
    PERMISSIONS.COLLECTE_CREATE,
  ],
  [ROLES.GESTIONNAIRE]: [
    PERMISSIONS.SIGNALER_READ,
    PERMISSIONS.SIGNALER_UPDATE,
    PERMISSIONS.CONTAINERS_READ,
    PERMISSIONS.CONTAINERS_UPDATE,
    PERMISSIONS.TOURNEE_CREATE,
    PERMISSIONS.TOURNEE_READ,
    PERMISSIONS.TOURNEE_UPDATE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.ANALYTICS_READ,
  ],
  [ROLES.ADMIN]: ['*'],
};

export const MOBILE_ROLES = [ROLES.CITOYEN, ROLES.AGENT];
export const DESKTOP_ROLES = [ROLES.GESTIONNAIRE, ROLES.ADMIN];
